<html>
<head>
<title>EPIC - CDB MapServer </title>
<style type="text/css">
<!--
body {  font-family: Arial, Helvetica, sans-serif; font-size: 12px} -->
</style>
</head>
<body bgcolor="#FFFFFF" text="#000000" link="#0000FF">
<h1>EPIC- CDB MapServer - version 1.0.0</h1>
<h2>Introduction</h2>
<p>Welcome to EPIC Builder v1.0.0, CDB MapServices for Windows, developed by
 <a href="https://www.vatcinc.com" target="_blank">Visual Awarness Technologies and Consulting Inc</a> <a href="https://www.epicready.com" target="_blank">EPIC Ready</a>.
</p>
<h2>Service End Points</h2>
<p>  Imagery (WMS) <a href="http://BuilderServices.EPICReady.com/mapserv/wms?Service=WMS&Request=GetCapabilities" target="_blank">BuilderServices.EPICReady.com/mapserv/wms</a> </p>
<p>  Elevation (WCS) <a href="http://BuilderServices.EPICReady.com/mapserv/wcs?Service=WCS&Request=GetCapabilities" target="_blank">BuilderServices.EPICReady.com/mapserv/wcs</a> </p>
<p>  Map Features (WFS) <a href="http://BuilderServices.EPICReady.com/mapserv/wfs?Service=WFS&Request=GetCapabilities" target="_blank">BuilderServices.EPICReady.com/mapserv/wfs</a> </p>
<p>  3D Model Features (WFS) <a href="http://BuilderServices.EPICReady.com/mapserv/wfsf?Service=WFS&Request=GetCapabilities" target="_blank">BuilderServices.EPICReady.com/mapserv/wfsf</a> </p>
<p>EPIC CDB Test Map:</p>
<h2>CDB Test Map</h2>
<iframe name="CDB test map" width="1280" height="1024" frameborder="0" scrolling="no" src="/cgi-bin/mapserv.exe?map=C:/EPIC_Ready/apps/cdb-demo/cdb.map&MODE=browse&TEMPLATE=openlayers&LAYERS=all"></iframe>
  <li>mapfile at <i>C:/EPIC_Ready/apps/cdb-demo/cdb.map</i></li>
  <li>open map viewer in new <a href="/cgi-bin/mapserv.exe?map=C:/EPIC_Ready/apps/cdb-demo/cdb.map&MODE=browse&TEMPLATE=openlayers&LAYERS=all" target="_blank">window</a></li>
</body>
</html>
